# Generated by Django 4.1 on 2022-08-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_anwa', '0002_alter_participate_point_alter_participate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betting',
            name='date',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='betting',
            name='time',
            field=models.CharField(max_length=6),
        ),
    ]
